### ISSUE TITLE
Account Creation and States

### ISSUE THREAD

**Issue by chludwig-haufe** [Haufe-Lexware/api-user-management#11]
I know I  am quite late in the game, but nevertheless: The documentation of `POST /users` does not tell me which elements of the response body are mandatory and how omitting them influences the created account. 

In particular, if I'd like to create a "pending" or "incomplete" account where all we know is the email address (scenario: newsletter registration), is it ok to simply submit the following response body?

```javascript
{
  "emails": [ { "value": "inbox@domain.org" } ]
}
```

**Comment by toraonaca** [comment]
You are right, I will add all the mandatory fields to all requests, and more details to each method.
