### ISSUE TITLE
/users/{id} contradicting parameters?

### ISSUE THREAD

**Issue by marc00s** [Haufe-Lexware/api-user-management#12]
Hi,

just a minor one: I can specify which fields to be included in the response, but I also can set extended to true or false. What will happen if I set it to true (full record), but also specify a couple of fields (part of the record)?

**Comment by toraonaca** [comment]
You get only the specified fields.

**Comment by marc00s** [comment]
Ok, thanks. I think we should update the description to make it clearer to the developer.
