### ISSUE TITLE
user attributes vs. additional_info

### ISSUE THREAD

**Issue by chludwig-haufe** [Haufe-Lexware/api-user-management#14]
For users, we have two sub-resources: 
* attributes (qualified with a {type}) and
* additional_info (qualified with a {name})

What is the conceptual difference between the two? Or to put it differently: Why do we need two different sub-resources?

For instance, haufe.de makes use of the community alias. (I am refering to the element `CommunityAlias` of the existing service's usermanagement10.xsd.) Why do we need to fetch that via `/users/{id}/additional_info/community_alias` rather than `/users/{id}/attributes/community_alias`? 

Cheers,
Christoph

**Comment by toraonaca** [comment]
Attributes was thought for emails, phones, ims and such (as designed here: https://tools.ietf.org/html/draft-ietf-scim-core-schema-22 - multivalue attribute). Additional_info was ported from the old user management. I think attributes would actually work for both. Moreso, with the existence of primary, we can store multi values for the same type (potentially, it's not yet designed like that).

**Comment by toraonaca** [comment]
I will rename attributes to communications so it's a more suggestive title. Attributes will be the same as additional infos, which will hold all the extra information that needs to be stored for a user. It will also be a multi-value map, so we can cover sa much ground as possible.
