### ISSUE TITLE
additional_info for multiple users

### ISSUE THREAD

**Issue by chludwig-haufe** [Haufe-Lexware/api-user-management#15]
I have seen that a GET on `/users` can return information (incl. additional_info) on multiple users. How can we select a specific set of users whose info we are interested in?

To give a specific example, haufe.de submits a request to `/users/userlist` against the existing system to get the alias of all users who commented on a particular article. Is there an equivalent call in the new user management API?

Given the fact that we have only very few comments on our articles, it won't cause practical problems for haufe.de or load issues for the user management service if we have to submit multiple requests, one per user. I want to make sure that there is a conscious decision how to handle such cases, though.

Cheers,
Christoph

**Comment by toraonaca** [comment]
Do you send the huids or user ids or emails? I was thinking of having something like /users?emails=a,b,c&fields=d,e,f. That you give back the least amount of information.

Also, there's the users/seaches/{id} resource that would return the list of users after a seach has been placed with a post on /users/searches. The /users would work with the db while the searches resources work with solr. I initially thought the searches resources should be used for batch queries, but we can expand the filtering capabilities of the /users resource as well.

**Comment by chludwig-haufe** [comment]
So far, we submit a list of HMG user ids. If Helios can submit multiple `haufe_external_user_id`s as a comma-separated list, then that's perfect.

**Comment by toraonaca** [comment]
Ok, I added that in the design.
