### ISSUE TITLE
id, external_id, sap_id is confusing

### ISSUE THREAD

**Issue by mitraman** [Haufe-Lexware/api-user-management#7]
it's not clear to me why all of these IDs needs to be supported.  In some of the calls (e.g. POST /companies both an ID and external ID are documented).  To add to the confusion, sometimes the external ID is referred to as a SAP ID.

**Comment by toraonaca** [comment]
The system interacts with SAP for most of the operations. In order for SAP to understand the data, we need to send them their own IDs. So we need to store them.
SAP can call us to register a new user. They will send their own id then.
Also, we have to support legacy systems, old systems that had their own ids for a user, and we have to store that value also. More so, there are other systems still relying on that type of id. 

Maybe redo the naming: sap_external_id and hssi_external_id?

**Comment by toraonaca** [comment]
Or, we already have an additional_info list that contains a bunch of key/value pairs of things that are additional to the user data, but we need to store for external systems. We can store these external ids there.

**Comment by toraonaca** [comment]
Actually, this was another thing I was struggling with, if i should expose /additional_info instead of allowing PATCH on users/{id}.

**Comment by mitraman** [comment]
If I understand correctly, when a client application (e.g. the SAP system) creates a new object, it is allowed to provide an ID property of it's own that the API will store.  Correct?

It sounds like this is some kind of convenience feature that frees clients from doing the ID mapping themselves.  If this is true and the API doesn't actually do anything with this field other than echo it back to clients, you could potentially store that data in generic name-value bucket like you describe:

```javascript
{
   stuff: [
      {name: 'SAP_id', value: '13'}
   ],
   company_name: "hauffe-lexware",
   department: "support"
}
```

This will help you to avoid designing for everyone's unique ID mapping needs.  But, it opens up a whole new can of worms... do all clients of this API use those mapped IDs?  Do different clients have different mapping needs?  What if one client wipes out another client's id mapping data?  Can these mappings change over time?  What happens if SAP is replaced by some other system?  What if some clients are case-senstive while others are not?

Make sure you work out all of these scenarios and have a way of supporting the desired behaviour.  

Essentially, you are designing a new behaviour: mapping.  Putting usability and optimisation aside, you might have even modelled this as a new resource:

```javascript
POST /idMap
{
  sourceId: 14,
  SAP_Id: 'sooi1ijfsi'
}

GET /idMap?target=SAP&id=14
{
  sourceId: 14,
  SAP_Id: 'sooi1ijfsi'
}
```

This has the disadvantage that the client has to made additional calls and must do the work of saving a newly created ID in the system themselves.  But, has the advantage of simplifying the create, read and update interactions for Companies and Users.

You'll need to apply the 80/20 principle and decide which type of behaviour is going to be most prevalent for users of the API.  If most of the creates and reads will require mapping it makes sense to batch them together the way you describe.

But, do your best to make the names of these things less confusing.  Also, make sure you provide special documentation for these concepts if they are as confusing for your target developers as they are for me.

**Comment by toraonaca** [comment]
I renamed all external ids in a more meaningful way.
