### ISSUE TITLE
GET /companies/{id}/payment_method returns an object

### ISSUE THREAD

**Issue by mitraman** [Haufe-Lexware/api-user-management#8]
This might be ok, but currently this API call returns a single payment method object.  Once this is implemented you will never be able to support a scenario where a company has multiple payment methods without making a breaking change.

This situation is made more confusing by the POST /companies/{id}/payment_method operation.  I can create multiple payment methods, but can only retrieve a single method?

**Comment by toraonaca** [comment]
For now, a company can have only one payment method. Maybe we can add more in the future. If we do a /payment_methods collection and allow a POST to create a new payment_method, won't we have the same problem (right now when we only have one)?

**Comment by mitraman** [comment]
If the company can only have one payment method, what happens if I call `POST /companies/{id}/payment_method` twice?

**Comment by toraonaca** [comment]
Will fail. Maybe we should just allow PUT for creation/update.

**Comment by toraonaca** [comment]
I actually need advice with this. If I have a subresource that is not part of a collection, it's just one (like one address, one payment method), should I use PUT for create and update?  In this case the client must provide the id, right?

**Comment by toraonaca** [comment]
I only left GET, PUT and DELETE on the single resource. PUT when no value exists, returns 201. When updating, returns 204.
